id = "wgsl-analyzer"
name = "Wgsl Analyzer"
version = "0.0.2"
schema_version = 1
authors = ["Arlo Phoenix <aarlo.phoenix@gmail.com>"]
description = "Wgsl language support for Zed"
repository = "https://github.com/luan/zed-wgsl"
path_suffixes = ["wgsl"]

[language_servers.wgsl]
name = "Wgsl Analyzer"
language = "Wgsl"

[grammars.wgsl]
repository = "https://github.com/szebniok/tree-sitter-wgsl"
commit = "40259f3c77ea856841a4e0c4c807705f3e4a2b65"
